### ISSUE TITLE
Missing ability to get open ports

### ISSUE THREAD

**Issue by oxysoft** [vast-ai/vast-python#112]
I am opening ports like this: `--env '-p 8188:8188'`. The real effective port is shown in the console on the website and doesn't appear to be retrievable from this script, which is a problem since I want to automate a lot of separate instances.

**Comment by twinnedAI** [comment]
@oxysoft you can get the port mapping of an instance by using the `raw` flag. This returns a json object with all informations:

**CLI**:
`vastai show instance <id> --raw`

**Python**:
`client = VastAI(api_key='1234', raw=True)`

**Comment by jsbcannell** [comment]
closed
