### ISSUE TITLE
create a requirements.txt

### ISSUE THREAD

**Issue by trollwookiee** [vast-ai/vast-python#27]
Could you please create a requirements.txt?

This way user doesn't have to manually install all packages and deal with errors like:
$ ./vast.py show invoices
ERROR: This library depends on a Python package called Borb to make the PDF files. To install this 
    package do 'pip3 install borb'.

**Comment by dweremeichik** [comment]
It appears that this was fixed in c921685357887c88c8fc8b22709bfea1c8a308d3
