### ISSUE TITLE
datacenter filter

### ISSUE THREAD

**Issue by magicrobotmonkey** [vast-ai/vast-python#38]
I'm trying to only use datacenter GPUs. In the web console, I'm able to filter by a "datacenter" field. When I use vast.py I see the following: 

```
./vast search offers "datacenter==true"
Warning: Unrecognized field: datacenter, see list of recognized fields.
```
 It still returns a handful of offers, but also returns no offers at all when doing `datacenter==false` so I'm not sure what's going on...

**Comment by dweremeichik** [comment]
Looking through the code, there is no reference to `datacenter`. It looks like they may have added this as an alias at some point for their site and never added an alias to the CLI. Referencing the network tab (developer tools) on their site and the documentation, you probably want to use `external` see [here](https://docs.vast.ai/command-line-interface/commands#search-offers-search-for-instance-types-using-custom-query). It also appears that the default behaviour for the CLI is to use `external  = false` (aka `datacenter` only).
