### ISSUE TITLE
Please add location (US, TW, etc.) to search offers

### ISSUE THREAD

**Issue by avocardio** [vast-ai/vast-python#41]
It would really help to filter out bad latency connections. Thanks!

**Comment by nathanneuro** [comment]
It makes sense that you'd want to be able to filter by geolocation. Unfortunately, adding this filter to the query will be a bit tricky so we probably won't get to that soon. It would be pretty straightforward to add it as a local filter to drop some of the results that the query returns. I'll take a look and see if I can add that.
