### ISSUE TITLE
Create subaccount response 400: Invalid json body

### ISSUE THREAD

**Issue by rybnovdws** [vast-ai/vast-python#52]
Hello.
Trying to create subaccount using new function (create subaccount from https://github.com/vast-ai/vast-python/pull/48).
`python3 vast.py create subaccount --email ****@****.*** --username ****** --password *********** --type host`
with valid api key 
`failed with error 400: Subaccount not approved`
Am I doing something wrong? Or is there some other issue with it?

**Comment by jsbcannell** [comment]
Creation of sub accounts requires specific approval for various reasons.  I believe you already contacted us; for anyone else reading this you'll need to contact us to enable this capability.
